### ISSUE TITLE
[REFACTOR] setup armies database script

### ISSUE THREAD

**Issue by Victoire-Rabeau** [Prophecy-eip/Backend#54]
## TODO

- [ ] Rename script: `setup armies database` -> `setup armies data`
- [ ] All class members must become private
- [ ] Add getters for private class members
- [x] Create a file for each class
- [ ] Add a limits serializer helper function
- [x] Create a file for helper functions
- [ ] Create const variables for tables columns names and content
- [x] get One array of each type in army class and only fill this one, and link with id in other classes

**Comment by Victoire-Rabeau** [comment]
the script was entirely refoactored, so I'm closing this issue
